### ISSUE TITLE
Cast issue 

### ISSUE THREAD

**Issue by Guillelerial** [analucfer/macFingerprinting#2]
> arreglé lo de la base de datos y, ejecutándolo con mongodb y mac_info como parametros (porque mac research tiene 26 millones de documentos y tarda siglos en procesarlos) llego otra vez a un problema en la linea 724 pero que no quiero arreglar ahí en realidad porque esa función se usa en más sitios, y creía que lo habçia arreglado desde donde se le llama pero no funchiona

Load dataset via https://zenodo.org/record/545970#.X7mQoC0rxQK

**Comment by analucfer** [comment]
Fixed
